version: '3'

services:

  my_app:
    build:
      context: .
      dockerfile: Dockerfile2

    ports:
      - '8080'

    deploy:
      replicas: 4

    restart: always

    environment:
      - PORT=8080
      - PING_LISTEN_PORT=8000

    networks:
      - front

    volumes:
      - db_data:/app/bdd.db

  proxy:
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - 8000:80
    
    depends_on:
      - my_app

    networks:
      - front

networks:
  front:
    driver: bridge

volumes:
  db_data:

  
